#ifndef __IWRAP_H
#define __IWRAP_H

#define EVENT_TRACK_CHANGED "AVRCP PDU 31 2 \n"
#define AVRCP_GET_ARTIST_TITLE "AVRCP PDU 20 2 1 2 \n"
#define AVRCP_PLAY "AVRCP PLAY \n"
#define AVRCP_PAUSE "AVRCP PAUSE \n"
#define AVRCP_NEXT "AVRCP FORWARD \n"
#define AVRCP_PREV "AVRCP BACKWARD \n"
#define AVRCP_GET_PLAY_STATUS "AVRCP PDU 30 \n"

#endif
